CC=gcc
CFLAGS=-DHAVE_CONFIG_H -DPIC -D__APPLE__ -DHAVE_PCSC -D__OLD_PCSC_API__ -DHAVE_OPENSSL -fno-strict-aliasing -g -O2 -no-cpp-precomp -MD -MP  -c -fno-common -I. -I../.. -I../../src/include

OBJS = scdl.o

INSTALL_HEADERS=scdl.h
HEADERS=$(INSTALL_HEADERS)
INCLUDE_DIR=../include/opensc

all: $(OBJS) copy_headers

clean:
	- rm *.o
	- rm *.d

$(OBJS): $(HEADERS)

copy_headers:
	if test $(INCLUDE_DIR)/scdl.h -ot scdl.h; then cp -f scdl.h $(INCLUDE_DIR); fi;
