all:
	echo "=========== Making OpenSC things (lib, pkcs11, tools)  ========="
	cd src && $(MAKE) $(AM_MAKEFLAGS) -f Makefile.mac && cd ..

clean:
	cd src && $(MAKE) $(AM_MAKEFLAGS) -f Makefile.mac clean && cd ..

install:
	cd src && $(MAKE) $(AM_MAKEFLAGS) -f Makefile.mac install && cd ..

uninstall:
	cd src && $(MAKE) $(AM_MAKEFLAGS) -f Makefile.mac uninstall && cd ..
